name: DOCTL

on:
  push:
    branches:
      - main
    paths:
      - "config/**"
      - "site/**"
      - "Dockerfile"
      - ".github/workflows/**"

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    env:
      vpc_id: 8b2459ae-a292-450a-84b8-7a31372b9264
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get reverse proxy drolet
        run: doctl compute droplet get nginx -o json

      - name: List VPCs
        run: doctl vpcs list

      - name: Get all web server drolets
        run: doctl compute droplet list --tag-name web-server --format "ID,Name,PublicIPv4,PrivateIPv4" > servers.in.txt

      - name: Process web servers list
        run: |
          chmod +x ./process_server_ips.sh
          ./process_server_ips.sh servers.in.txt servers.out.txt
          cat servers.out.txt
