name: DOCTL

on:
  push:
    branches:
      - main
    paths:
      - "config/**"
      - "site/**"
      - "Dockerfile"
      - ".github/workflows/**"

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get reverse proxy drolet
        run: doctl compute droplet get nginx -o json

      - name: Get all web server drolets
        run: doctl compute droplet list --tag-name web-server --format ID,Name,PublicIPv4,PrivateIPv4,Region,Tags -o json > web_servers.json

      - name: Process web servers list
        run: cat web_servers.json
